<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {reactive,ref} from 'vue';import {request} from '../api'
const fields=[{"key": "inventoryNo", "label": "碳盘查编号", "type": "text"}, {"key": "activityDataCoverage", "label": "活动数据覆盖率(%)", "type": "number"}, {"key": "factorCoverage", "label": "排放因子覆盖率(%)", "type": "number"}, {"key": "verificationPassRate", "label": "核证抽样通过率(%)", "type": "number"}, {"key": "forecastReductionRate", "label": "预测减排率(%)", "type": "number"}, {"key": "targetReductionRate", "label": "目标减排率(%)", "type": "number"}, {"key": "unresolvedAnomalies", "label": "未解决异常数", "type": "number"}, {"key": "methodologyApproved", "label": "核算方法已审批", "type": "boolean"}, {"key": "independentVerified", "label": "已完成独立核证", "type": "boolean"}]
const form=reactive({"inventoryNo": "GHG-2026-001", "activityDataCoverage": 98, "factorCoverage": 100, "verificationPassRate": 97, "forecastReductionRate": 12, "targetReductionRate": 10, "unresolvedAnomalies": 0, "methodologyApproved": true, "independentVerified": true}),result=ref(null),error=ref(''),busy=ref(false)
function payload(){const data={};for(const field of fields){const value=form[field.key];if(field.type==='number')data[field.key]=Number(value);else data[field.key]=value}return data}
async function run(){busy.value=true;error.value='';try{result.value=await request('/api/domain/decision',{method:'POST',body:JSON.stringify(payload())})}catch(e){error.value=e.message}finally{busy.value=false}}
const show=value=>Array.isArray(value)?(value.length?value.join('；'):'无'):typeof value==='object'?JSON.stringify(value):String(value)
const engineResult=ref(null),engineError=ref(''),engineBusy=ref(false)
async function runEngine(){engineBusy.value=true;engineError.value='';try{engineResult.value=await request('/api/domain/emission-inventory',{method:'POST',body:JSON.stringify({targetTco2e:5,activities:[{lineId:'A-1',sourceName:'天然气',scope:'SCOPE_1',activityAmount:1000,factorKgCo2ePerUnit:2.1,factorVersion:'CN-2026',uncertaintyPercent:5,evidenceAttached:true},{lineId:'A-2',sourceName:'外购电力',scope:'SCOPE_2_LOCATION',activityAmount:10000,factorKgCo2ePerUnit:.57,factorVersion:'GRID-2026',uncertaintyPercent:8,evidenceAttached:true}],reductionProjects:[{projectCode:'PV-01',expectedReductionTco2e:3}]})})}catch(e){engineError.value=e.message}finally{engineBusy.value=false}}
</script>
<template><section class="rule-head"><div><span>DOMAIN CONTROL</span><h3>AI碳核算与减排管理系统领域规则验证</h3><p>统一活动数据、排放因子、碳盘查、异常识别与减排情景，形成可验证碳管理闭环，由服务端返回可审计决策、评分、指标和处置动作。</p></div><b>服务端强校验</b></section><section class="rule-layout"><form class="rule-form" @submit.prevent="run"><label v-for="field in fields" :key="field.key"><span>{{field.label}}</span><span v-if="field.type==='boolean'" class="switch"><input v-model="form[field.key]" type="checkbox">{{form[field.key]?'是':'否'}}</span><input v-else v-model="form[field.key]" :type="field.type" :step="field.type==='number'?'any':undefined" required></label><button class="run" :disabled="busy">{{busy?'正在校验…':'执行规则校验'}}</button><p v-if="error" class="rule-error">{{error}}</p></form><aside class="result"><template v-if="result"><span>DECISION</span><h3>{{result.decision}}</h3><strong>评分 {{result.score}} / 100</strong><dl><template v-for="(value,key) in result.metrics" :key="key"><dt>{{key}}</dt><dd>{{show(value)}}</dd></template></dl><h4>处置动作</h4><p v-for="item in result.actions" :key="item">· {{item}}</p></template><div v-else class="empty"><b>等待评估</b><p>填写业务数据后执行企业级领域规则。</p></div></aside></section><section class="engine"><div><span>GHG INVENTORY</span><h3>碳排放清册与目标差距</h3><p>按活动数据和因子版本核算范围一、二、三排放，评估凭证覆盖、加权不确定性及减排项目后的目标差距。</p><button class="run" :disabled="engineBusy" @click="runEngine">{{engineBusy?'核算中…':'运行碳清册示例'}}</button><p v-if="engineError" class="rule-error">{{engineError}}</p></div><pre>{{engineResult?JSON.stringify(engineResult,null,2):'等待运行核心引擎'}}</pre></section></template>
<style scoped>.rule-head{display:flex;align-items:end;justify-content:space-between;padding:26px 30px;margin-bottom:18px;background:#fff;border:1px solid #e2e8eb;border-radius:14px}.rule-head span,.result>span{font-size:12px;letter-spacing:.16em;color:#61727b}.rule-head h3{font-size:24px;margin:7px 0}.rule-head p{margin:0;color:#667780}.rule-head>b{padding:8px 12px;border-radius:20px;background:#e8f3ee;color:#237052;font-size:13px}.rule-layout{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:18px}.rule-form,.result{background:#fff;border:1px solid #e2e8eb;border-radius:14px;padding:28px}.rule-form{display:grid;grid-template-columns:1fr 1fr;gap:18px}.rule-form label{display:flex;flex-direction:column;gap:8px;font-size:13px;color:#44545d}.rule-form input{box-sizing:border-box;width:100%;border:1px solid #ccd6db;border-radius:8px;padding:11px 12px;font:inherit;background:#fbfcfd}.switch{display:flex;align-items:center;gap:8px;height:40px}.switch input{width:18px}.run,.rule-error{grid-column:1/-1}.run{border:0;border-radius:8px;padding:13px;background:#234f66;color:#fff;font-weight:700}.result h3{font-size:25px;margin:8px 0}.result dl{margin:15px 0}.result dt{font-size:12px;color:#78868e;margin-top:10px}.result dd{margin:3px 0;border-bottom:1px solid #edf0f2;padding-bottom:8px}.empty{display:grid;place-content:center;min-height:260px;color:#75838a}.rule-error{color:#a53535}@media(max-width:900px){.rule-layout{grid-template-columns:1fr}.rule-form{grid-template-columns:1fr}}</style>
